name: dementia_assist_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Voice
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.5

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_database: ^12.0.4
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4
  google_generative_ai: ^0.4.6
  intl: ^0.20.2
  permission_handler: ^11.0.1


  # Notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # Background voice service (correct versions!)
  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
